<div id="dashboard">
    <form action="<?php echo $this->baseUrl() . '/admin/menu/content-search'; ?>" method="post">
        <div id="all-search-wrapper">
            <div id="search-field-wrapper">
                <input type="text" name="searchtext" placeholder="Search Content or Navigation" id="search-all-content"/>
            </div>
            <div id="search-type-wrapper">
                <select name="menu_type" id="menu-type">
                    <option value="menu">Navigation</option>
                    <option value="content">Content</option>
                </select>
            </div>
            <div id="search-submit-wrapper">
                <input type="submit" id="search-submit" name="submit" value="Search"/>
            </div>
            <div class="clear"></div>
        </div>
    </form>
    <div id="search-result">
        <div class="dashboard-item">
            <a href="<?php echo $this->baseUrl() . '/admin/menu/add-content'; ?>">Add Content</a>
        </div>
        <div class="dashboard-item">
            <a href="<?php echo $this->baseUrl() . '/admin/staff/attendance'; ?>">Staff Attendance</a>
        </div>
        <div class="dashboard-item">
            <a href="<?php echo $this->baseUrl() . '/admin/studentfee'; ?>">Student Fee</a>
        </div>
        <div class="dashboard-item">
            <a href="<?php echo $this->baseUrl() . '/admin/gallery/list'; ?>">Photo Gallery</a>
        </div>
        <div class="dashboard-item">
            <a href="<?php echo $this->baseUrl() . '/admin/student/attendance'; ?>">Student Attendance</a>
        </div>
        <div class="dashboard-item">
            <a href="<?php echo $this->baseUrl() . '/admin/student/upgrade'; ?>">Upgrade Class</a>
        </div>

        <div class="dashboard-item">
            <a href="<?php echo $this->baseUrl() . '/admin/news/add'; ?>">Add News feed</a>
        </div>
        <div class="dashboard-item">
            <a href="<?php echo $this->baseUrl() . '/admin/student/add'; ?>">Add Student</a>
        </div>
        <div class="dashboard-item">
            <a href="<?php echo $this->baseUrl() . '/admin/finance/list'; ?>">School Finance</a>
        </div>
        <div class="dashboard-item">
            <a href="<?php echo $this->baseUrl() . '/admin/result/search'; ?>">Search Result</a>
        </div>
        <div class="dashboard-item">
            <a href="<?php echo $this->baseUrl() . '/admin/result'; ?>"> Add Result</a>
        </div>
        <div class="dashboard-item">
            <a href="<?php echo $this->baseUrl() . '/admin/examtype/add'; ?>">Add Exam Type</a>
        </div>
        <div class="dashboard-item">
            <a href="<?php echo $this->baseUrl() . '/admin/staff/add'; ?>">Add Staff</a>
        </div>
        <div class="dashboard-item">
            <a href="<?php echo $this->baseUrl() . '/admin/subject/add'; ?>">Add Subject</a>
        </div>
        <div class="dashboard-item">
            <a href="<?php echo $this->baseUrl() . '/admin/gallery/add'; ?>">Add Gallery</a>
        </div>
        <div class="dashboard-item">
            <a href="<?php echo $this->baseUrl() . '/admin/image/add'; ?>">Add Image</a>
        </div>
        <div class="dashboard-item">
            <a href="<?php echo $this->baseUrl() . '/admin/index/theme'; ?>">Change Theme</a>
        </div>
    </div>
</div>
<?php $this->headScript()->appendFile($this->baseUrl() . '/school/admin/js/content-search.js'); ?>