<div id="dashboard">
    <div class="dashboard-item">
        <a href="<?php echo $this->baseUrl() . '/admin/menu/add-content'; ?>">Add Content</a>
    </div>
    <div class="dashboard-item">
        <a href="<?php echo $this->baseUrl() . '/admin/news/add'; ?>">Add News feed</a>
    </div>
    <div class="dashboard-item">
        <a href="<?php echo $this->baseUrl() . '/admin/student/add'; ?>">Add Student</a>
    </div>
    <div class="dashboard-item">
        <a href="<?php echo $this->baseUrl() . '/admin/menu/content-search'; ?>">Search Content</a>
    </div>
    <div class="dashboard-item">
        <a href="<?php echo $this->baseUrl() . '/admin/finance/list'; ?>">Finance List</a>
    </div>
    <div class="dashboard-item">
        <a href="<?php echo $this->baseUrl() . '/admin/result/search'; ?>">Search Result</a>
    </div>
    <div class="dashboard-item">
        <a href="<?php echo $this->baseUrl() . '/admin/result'; ?>"> Add Result</a>
    </div>
    <div class="dashboard-item">
        <a href="<?php echo $this->baseUrl() . '/admin/examtype/add'; ?>">Add Exam Type</a>
    </div>
    <div class="dashboard-item">
        <a href="<?php echo $this->baseUrl() . '/admin/staff/add'; ?>">Add Staff</a>
    </div>
    <div class="dashboard-item">
        <a href="<?php echo $this->baseUrl() . '/admin/subject/add'; ?>">Add Subject</a>
    </div>
    <div class="dashboard-item">
        <a href="<?php echo $this->baseUrl() . '/admin/gallery/add'; ?>">Add Gallery</a>
    </div>
    <div class="dashboard-item">
        <a href="<?php echo $this->baseUrl() . '/admin/image/add'; ?>">Add Image</a>
    </div>
    <div class="dashboard-item">
        <a href="<?php echo $this->baseUrl() . '/admin/menu/navigation'; ?>">Menu Navigation</a>
    </div>
    <div class="dashboard-item">
        <a href="<?php echo $this->baseUrl() . '/admin/index/theme'; ?>">Change Theme</a>
    </div>
</div>