<link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl() . '/school/admin/css/united.css'; ?>">
<script type="text/javascript" src="<?php echo $this->baseUrl() . '/school/admin/js/jquery-1.8.js' ?>"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl() . '/school/admin/js/list.js' ?>"></script>
<table align="right" width="100%" border="1px solid black">
    <tr>
        <th>Front Menu ID</th>
        <th>Title</th>
        <th>Content</th>
        <th>parent menu ID</th>
        <th>Entered Date</th>
        <th>Updated Date</th>
        <th>Show/Hide</th>
        <th>Edit</th>
        <th>Delete</th>
    </tr>
    <?php foreach ($this->result as $result): ?>

        <tr>
            <td><?php echo $result['front_menu_id']; ?></td>
            <td><?php echo $result['title']; ?></td>
            <td><?php echo $result['content']; ?></td>
            <td><?php echo $result['parent_menu_id']; ?></td>
            <td><?php echo $result['entered_date']; ?></td>
            <td><?php echo $result['update_date']; ?></td>
            <td>
                <?php $permClass = ($result['sh'] == 'Y') ? "permitted" : "notpermitted"; ?>
                <a class="<?php echo $permClass; ?>" href="<?php echo $this->url(array("controller" => "menu", "action" => "status", "id" => $result['front_menu_id'])); ?>"> &nbsp;&nbsp;&nbsp;&nbsp;</a>
            </td>
            <td>
                <a href="<?php echo $this->url(array('controller' => 'menu', 'action' => 'edit', 'id' => $result['front_menu_id'])); ?>">Edit </a>
            </td>
            <td>
                <a href="<?php echo $this->url(array('controller' => 'menu', 'action' => 'delete', 'id' => $result['front_menu_id'])); ?>">Delete</a>
            </td>
        </tr>
    <?php endforeach; ?>
</table>
<?php
;
$front = Zend_Controller_Front::getInstance()->getRequest();
$module = $front->getModuleName();
$controller = $front->getControllerName();
$actionPath = '/' . $module . '/' . $controller . '/';
?>
<input class="action-path" type="hidden" name="action_path" value="<?php echo $actionPath; ?>" />
