<html>
    <head>
        <title>
            School Management System
        </title>
        <?php
        $this->headLink()->appendStylesheet($this->baseUrl() . "/school/admin/css/style.css");
        $this->headScript()->appendFile($this->baseUrl() . "/common/js/jquery-1.7.2.min.js");
        $this->headScript()->appendFile($this->baseUrl() . "/common/js/jquery-ui-1.8.21.custom.min.js");
        $this->headLink()->appendStylesheet($this->baseUrl() . "/common/css/jquery-ui-1.8.21.custom.css");
        echo $this->headLink();
        echo $this->headScript();
        ?>
    </head>
    <body>
        <div id="container">
            <div id="top-navigation">
                <ul class="nav">
                    <li><a href="<?php echo $this->baseUrl() . '/admin/student/list'; ?>">Students</a></li>
                    <li><a href="<?php echo $this->baseUrl() . '/admin/staff/list'; ?>">Staff</a></li>
                    <li><a href="<?php echo $this->baseUrl() . '/admin/subject/list'; ?>">Subjects</a></li>
                    <li><a href="<?php echo $this->baseUrl() . '/admin/news/list'; ?>">News feed</a></li>
                    <li><a href="<?php echo $this->baseUrl() . '/admin/image/list'; ?>">Image</a></li>
                    <li><a href="<?php echo $this->baseUrl() . '/admin/gallery/list'; ?>">Gallery</a></li>
                    <?php if (Zend_Auth::getInstance()->hasIdentity()) { ?>
                        <li><a href="<?php echo $this->baseUrl() . '/admin/index/logout'; ?>">Logout</a></li>
<?php } ?>
                </ul>

            </div>
            <div id="application-content">
<?php echo $this->layout()->content; ?>
            </div>
        </div>
    </body>
</html>

