<?php $this->headLink()->appendStylesheet($this->baseUrl() . "/school/admin/css/table.css"); ?> 
<table id="CSS_Table">
    <tr>
        <th colspan="2"> Detail Information Of The Students</th>
        <th width="10"> <a style="text-decoration:none" href="<?php echo $this->url(array('controller' => 'student', 'action' => 'list')); ?>">Back</a></th>  
    </tr>
    <tr>
        <th> Roll No</th>
        <td><?php echo $this->result['roll_no']; ?></td>
    </tr>
    <tr>
        <th> Full Name</th>
        <td><?php echo $this->result['full_name']; ?></td>
    </tr>
    <tr>
        <th> Sex </th>
        <td><?php echo $this->result['sex']; ?></td>
    </tr>
    <tr>
        <th> Date of Birth </th>
        <td><?php echo $this->result['dob']; ?></td>
    </tr>
    <tr>
        <th> Email </th>
        <td><?php echo $this->result['email']; ?></td>
    </tr>
    <tr>
        <th> Phone </th>
        <td><?php echo $this->result['phone']; ?></td>
    </tr>
    <tr>
        <th> Guardian Name </th>
        <td><?php echo $this->result['guardian_name']; ?></td>
    </tr>
    <tr>
        <th> Year </th>
        <td><?php echo $this->result['year']; ?></td>
    </tr>
    <tr>
        <th> Class </th>
        <td><?php echo $this->result['grade']; ?></td>
    </tr>
    <tr>
        <th> Section </th>
        <td><?php echo $this->result['section']; ?></td>
    </tr>
</table>
<hr />
<?php
$arr = array();
foreach ($this->feetypes as $type) {
    $arr[$type['isMonthly']][] = $type;
}
?>
<?php if ($arr['N']) { ?>
    <table>
        <caption><h3>Annual Fee</h3></caption>
        <tr>
            <th>Title</th>
            <th>Due Amount</th>
            <th>Discount</th>
            <th>Total Amount</th>
            <th>Paid?</th>
            <th>Update</th>
        </tr>
        <?php foreach ($arr['N'] as $type) { ?>
            <tr>
                <td><?php echo $type['name']; ?></td>
                <td></td>
                <td></td>
                <td><?php echo $type['amount']; ?></td>
                <td></td>          
                <td><input type="submit" name="submit"value ="Update" /></td>
            </tr>
        <?php } ?>
    </table>
    <?php
}
if ($arr['Y']) {
    foreach ($arr['Y'] as $type) {
        ?>
        <table>
            <caption><h3><?php echo $type['name']; ?></h3></caption>
            <tr>
                <th>Month</th>
                <th>Due Amount</th>
                <th>Discount</th>
                <th>Total Amount</th>
                <th>Paid?</th>
                <th>Update</th>
            </tr>
            <?php foreach ($this->monthOptions as $option) { ?>
                <tr>
                    <td><?php echo $option; ?></td>
                    <td></td>
                    <td></td>
                    <td><?php echo $type['amount']; ?></td>
                    <td></td>            
                    <td><input type="submit" name="submit" value="Update" /></td>
                </tr>
            <?php } ?>
        </table>
        <?php
    }
}
?>

