<table align="right" width="100%" border="1px solid black">
    <tr>
        <th> Student ID        </th>
        <th> Roll No     </th>
        <th> Full Name         </th>
        <th> Email </th>
        <th> Phone </th>
        <th> Guardian Name </th>
        <th> Class </th>
        <th> Section </th>
    </tr>
    <?php foreach ($this->result as $result): ?>

        <tr>
            <td><?php echo $result['student_id']; ?></td>
            <td><?php echo $result['roll_no']; ?></td>
            <td><?php echo $result['full_name']; ?></td>
            <td><?php echo $result['email']; ?></td>
            <td><?php echo $result['phone']; ?></td>
            <td><?php echo $result['guardian_name']; ?></td>
            <td><?php echo $result['class']; ?></td>
            <td><?php echo $result['section']; ?></td>
        </tr>
    <?php endforeach; ?>
</table>
