<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <title></title>
        <link href="style.css" rel="stylesheet" type="text/css" />
    </head>
    <body>
        <div id="container">
            <div id="divwrapper">
                <div id="divheader"><img src="img/Capture.JPG" width="640" height="177" /></div>
                <div id="divLine">&nbsp; </div>
                <div id="divlinks">  
                    <div id="divNav">
                        <ul>
                            <li><a href="home.html">Home</a></li>
                            <li><a href="student.html">Student</a></li>
                            <li><a href="faculty.html">Faculty</a></li>
                            <li><a href="aboutus.html">AboutUs</a> </li>
                        </ul>
                    </div>
                </div>
            </div>
            <form action=""> 
                <div id="divdropwrapper">
                    <div class="form-item-wrapper">
                        <label>Year</label> 
                        <select name="Year" class="form-select">
                            <option value="2012">2012</option>
                            <option value="2011">2011</option>
                            <option value="2010">2010</option>
                            <option value="2009">2009</option>
                        </select>

                    </div>

                    <div class="form-item-wrapper">

                        <label>Class</label>
                        <select name="Class" class="form-select">
                            <option value="10">10</option>
                            <option value="9">9</option>
                            <option value="8">8</option>
                            <option value="7">7</option>
                            <option value="6">6</option>
                            <option value="5">5</option>
                            <option value="4">4</option>
                            <option value="3">3</option>
                            <option value="2">2</option>
                            <option value="1">1</option>
                        </select>
                    </div>

                    <div class="form-item-wrapper" id="submit-wrapper">

                      <label>Section</label>
                        <select name="Section" class="form-select">
                            <option value="A">A</option>
                            <option value="B">B</option>
                            <option value="C">C</option>
                            <option value="D">D</option>
                            <option value="E">E</option>
                            <option value="F">F</option>
                        </select>
                    </div>



                    <div class="form-item-wrapper">
                        <label>Exam Type</label>
                        <select name="Examtype" class="form-select">
                            <option value="Firstterm">First Term</option>
                            <option value="secondterm">Second Term</option>
                            <option value="Thirdterm">Third Term</option>
                            <option value="Final">Final Exam</option>
                            <option value="sentup">Sent Up</option>
                            <option value="SLC">SLC</option>
                        </select>
                    </div>
                    <div class="form-item-wrapper">
                        <br />
                        <input type="submit" value="Submit">
                    </div>
                    <div class="clear"></div>
                </div>
            </form>    



            <table>
                <tr>
                    <th>List Of Subjects </th>
                    <th>Enter Marks</th>
                </tr>
                <tr>
                    <td>C.English</td>
                    <td><input type="text" name="c.english"></td>
                </tr>
                <tr>
                    <td>Nepali</td>
                    <td><input type="text" name="nepali"></td>
                </tr>
                <tr>
                    <td>Math I</td>
                    <td><input type="text" name="math1"></td>
                </tr>
                <tr>
                    <td>Science</td>
                    <td><input type="text" name="science"></td>
                </tr>
                <tr>
                    <td>Social Studies </td>
                    <td><input type="text" name="social"></td>
                </tr>
                <td>Optional I</td>
                <td><input type="text" name="opt1"></td>
                </tr>
                <tr>
                    <td>optional II </td>
                    <td><input type="text" name="opt2"></td>
                </tr>



            </table>
        </div>


        </div>      
    </body>
</html>