<div id="dashboard">
    <div class="dashboard-item">
        <a href="<?php echo $this->baseUrl().'/admin/examtype/add'; ?>">Add Exam Type</a>
    </div>
     <div class="dashboard-item">
           <a href="<?php echo $this->baseUrl().'/admin/result/search'; ?>"> Add Result</a>
    </div>
     <div class="dashboard-item">
          <a href="<?php echo $this->baseUrl().'/admin/result/'; ?>"> Search Result</a>
    </div>
</div>